mysite/balticwave/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.ProductListView.as_view(), name='products'),
    path('products/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),
    path('product-like/<int:pk>', views.product_like, name="product_like"),
    path('favouriteproducts/<int:id>', views.favourite_prod_add, name='favourite-prod-add'),

    path('services/', views.ServiceListView.as_view(), name='services'),
    path('services/<int:pk>', views.ServiceDetailView.as_view(), name='service-detail'),

    path('search/', views.search, name='search'),
    path('myadverts/', views.advert_list, name='advert-list'),

    path('myproducts/', views.SellerProductsListView.as_view(), name='my-products'),
    path('myproducts/<int:pk>/update', views.ProductByUserUpdateView.as_view(), name='my-update-product'),
    path('myproducts/<int:pk>/delete', views.ProductByUserDeleteView.as_view(), name='my-delete-product'),
    path('myproducts/new', views.ProductByUserCreateView.as_view(), name='my-new-product'),
    path('myproducts/<int:pk>', views.SellerProductDetailView.as_view(), name='my-product'),

    path('myservices/', views.SellerServiceListView.as_view(), name='my-services'),
    path('myservices/<int:pk>/update', views.ServiceByUserUpdateView.as_view(), name='my-update-service'),
    path('myservices/<int:pk>/delete', views.ServiceByUserDeleteView.as_view(), name='my-delete-service'),
    path('myservices/new', views.ServiceByUserCreateView.as_view(), name='my-new-service'),
    path('myservices/<int:pk>', views.SellerServiceDetailView.as_view(), name='my-service'),


    path('myfavourites/', views.favourite_list, name='favourite-list'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('balticwave/', include('balticwave.urls')),
    path('', RedirectView.as_view(url='balticwave/', permanent=True)),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

mysite/balticwave/models.py
from django.db import models
from tinymce.models import HTMLField
from django.contrib.auth.models import User
from PIL import Image
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey



class Product(models.Model):
    product_name = models.CharField('Product name', max_length=40)
    product_seller = models.ForeignKey(to=User, on_delete=models.SET_NULL, null=True, blank=True)
    price = models.FloatField('Price', null=True, blank=True, default=0)
    short_description = HTMLField('Short description', max_length=200)
    description = HTMLField(default='No description')
    insDate = models.DateTimeField('Instance date', auto_now_add=True)
    product_thumbnail = models.ImageField('Thumbnail', upload_to='product_thumbnails', null=True, blank=True)
    image1 = models.ImageField('Image 1', upload_to='product_images', null=True, blank=True)
    image2 = models.ImageField('Image 2', upload_to='product_images', null=True, blank=True)
    image3 = models.ImageField('Image 3', upload_to='product_images', null=True, blank=True)
    image4 = models.ImageField('Image 4', upload_to='product_images', null=True, blank=True)
    image5 = models.ImageField('Image 5', upload_to='product_images', null=True, blank=True)
    image6 = models.ImageField('Image 6', upload_to='product_images', null=True, blank=True)
    likes = models.ManyToManyField(User, related_name='productlike')
    favourites = models.ManyToManyField(User, related_name='favourite', default=None, blank=True)
    CATEGORY_CHOICES = [
        ('UN', 'Undefined'),
        ('Accesories', (
        )
         ),
        ('Blocks', (
            ('SIN', 'Single block'),
            ('DUO', 'Double block'),
            ('TRIP', 'Triple+ block'),
            ('CL', 'Block with cleat'),
            ('UNS', 'Unspecified'),
        )
         ),
        ('Navigation', (
            ('COMP', 'Magnetic/Electronic Compass'),
            ('RAD', 'Radio station'),
            ('SEM', 'Sea map')
        )
         ),
        ('Hardware', (
            ('CLE', 'Cleat'),
            ('SHA', 'Shackle'),
            ('WIN', 'Winch'),
        )
         ),
        ('Sails', (
            ('MAN', 'Main sail'),
            ('JIB', 'Jib'),
            ('SPI', 'Spinnaker'),
            ('GEN', 'Genoa'),
        )
         ),
        ('Maintenance Equipment', (
            ('PAI', 'Paint'),
        )
         )
    ]
    CITY_CHOICES = [
        ('Klaipėda county', (
            ('KLP', 'Klaipėda'),
            ('PL', 'Palanga'),
            ('NID', 'Nida'),
        )
         ),
        ('Kaunas county', (
            ('KUN', 'Kaunas'),
            ('JON', 'Jonava'),
            ('KĖD', 'Kėdainiai')
        )
         ),
        ('Vilnius county', (
            ('VIL', 'Vilnius'),
            ('UKM', 'Ukmergė'),
            ('ELE', 'Elektrėnai'),

        )
         ),
        ('Šiauliai county', (
            ('ŠL', 'Šiauliai'),
            ('RAD', 'Radviliškis'),
            ('NJA', 'Naujoji Akmenė'),
        )
         ),
        ('UN', 'Undefined'),
    ]

    LOAN_STATUS = (
        ('a', 'Available'),
        ('r', 'Reserved'),
        ('t', 'Sold'),
    )
    type = models.ManyToManyField('ProductType')
    category = models.CharField(max_length=5, choices=CATEGORY_CHOICES, help_text='Category', default='UN')
    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='a', help_text='Status',)
    city = models.CharField(max_length=3, choices=CITY_CHOICES, help_text='City', default='UN')

    def display_type(self):
        return ' #'.join(type.product_type_name for type in self.type.all()[:5])

    def number_of_likes(self):
        return self.likes.count()
    def __str__(self):
        return (f'{self.product_name} | {self.product_seller}')


class Service(models.Model):
    service_name = models.CharField('Service name', max_length=200)
    service_seller = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    insDate = models.DateTimeField('Instance date', auto_now_add=True)
    description = HTMLField(default='No description')
    type = models.ManyToManyField('ServiceType')
    service_thumbnail = models.ImageField('Thumbnail', upload_to='service_thumbnails', null=True, blank=True)
    image1 = models.ImageField('Image 1', upload_to='product_images', null=True, blank=True)
    image2 = models.ImageField('Image 2', upload_to='product_images', null=True, blank=True)
    image3 = models.ImageField('Image 3', upload_to='product_images', null=True, blank=True)
    image4 = models.ImageField('Image 4', upload_to='product_images', null=True, blank=True)
    image5 = models.ImageField('Image 5', upload_to='product_images', null=True, blank=True)
    image6 = models.ImageField('Image 6', upload_to='product_images', null=True, blank=True)
    CATEGORY_CHOICES = [
        ('UN', 'Undefined'),
        ('Transportation', (
            ('YA', 'Yacht'),
            ('MB', 'Motor boat')
        )
         ),
        ('Refurbishment', (
            ('DE', 'Deck'),
            ('IN', 'Inside')
        )
         ),
        ('Storage', (
            ('SAI', 'Sailboat'),
            ('INV', 'Inventory')
        )
         ),
    ]
    CITY_CHOICES = [
        ('Klaipėda county', (
            ('KLP', 'Klaipėda'),
            ('PL', 'Palanga'),
            ('NID', 'Nida'),
        )
         ),
        ('Kaunas county', (
            ('KUN', 'Kaunas'),
            ('JON', 'Jonava'),
            ('KĖD', 'Kėdainiai')
        )
         ),
        ('Vilnius county', (
            ('VIL', 'Vilnius'),
            ('UKM', 'Ukmergė'),
            ('ELE', 'Elektrėnai'),

        )
         ),
        ('Šiauliai county', (
            ('ŠL', 'Šiauliai'),
            ('RAD', 'Radviliškis'),
            ('NJA', 'Naujoji Akmenė'),
        )
         ),
        ('UN', 'Undefined'),
    ]
    city = models.CharField(max_length=3, choices=CITY_CHOICES, help_text='City', default='UN')
    category = models.CharField(max_length=5, choices=CATEGORY_CHOICES, help_text='Category', default='UN')

    def display_type(self):
        return ' #'.join(type.service_type_name for type in self.type.all()[:5])
    def __str__(self):
        return (f'{self.service_name}')


class ServiceType(models.Model):
    service_type_name = models.CharField('Type', max_length=50)

    def __str__(self):
        return self.service_type_name
class ProductType(models.Model):
    product_type_name = models.CharField('Type', max_length=50)
    def __str__(self):
        return self.product_type_name

class ProductReview(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, null=True, blank=True, related_name='productreview')
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Review', max_length=2000)

    class Meta:
        ordering = ['-date_created']

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(default="profile_pics/default.png", upload_to="profile_pics")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.profile_pic.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.profile_pic.path)
    def __str__(self):
        return f'{self.user.username}'

mysite/balticwave/forms.py
from .models import Profile, Product, ProductReview, Service
from django import forms
from django.contrib.auth.models import User

class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = ProductReview
        fields = ('content', 'product', 'reviewer',)
        widgets = {'product': forms.HiddenInput(), 'reviewer': forms.HiddenInput()}
class DateInput(forms.DateInput):
    input_type = 'date'
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email']
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_pic']

class UserProductCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_name', 'price', 'short_description', 'description', 'category', 'type', 'product_thumbnail', 'image1', 'image2', 'image3', 'image4', 'image5', 'image6', 'city', 'status']
        widgets = {'product_seller': forms.HiddenInput(), 'insDate': DateInput()}

class UserServiceCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ('service_name', 'description', 'category', 'type', 'service_thumbnail')
        widgets = {'service_seller': forms.HiddenInput(), 'insDate': DateInput()}

mysite/balticwave/templates/advert_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container" style="margin-top:20px; margin-bottom:20px">
    <div class="row">
        <div class="col-sm-6">
            <h3>My products:</h3>
            {% if product_list %}
            {% for product in product_list %}
            <div class="media border p-3" style="margin-top:20px">
                {% if product.product_thumbnail %}
                <a href="{% url 'my-product' product.id %}"><img class="mr-3 mt-3 img-thumbnail"
                                                                     style="width:60px;"
                                                                     src="{{ product.product_thumbnail.url }}"></a>
                {% else %}
                <a href="{% url 'my-product' product.id %}"><img class="mr-3 mt-3 img-thumbnail"
                                                                     style="width:60px;"
                                                                     src="{% static 'img/no-image.png' %}"></a>
                {% endif %}
                <div class="media-body">
                    <h4><a href="{% url 'my-product' product.id %}">{{ product.product_name }}</a> <small><i>Posted
                        on: {{ product.insDate }}</i></small></h4>
                    <button><a href="{% url 'my-update-product' product.id %}">Update</a> </button>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>You have not posted any products.</p>
            {% endif %}
        </div>
        <div class="col-sm-6">
            <h3>My services:</h3>
            {% if service_list %}
            {% for service in service_list %}
            <div class="media border p-3" style="margin-top:20px">
                {% if service.service_thumbnail %}
                <a href="{% url 'my-service' service.id %}"><img class="mr-3 mt-3 img-thumbnail"
                                                                     style="width:60px;"
                                                                     src="{{ service.service_thumbnail.url }}"></a>
                {% else %}
                <a href="{% url 'my-service' service.id %}"><img class="mr-3 mt-3 img-thumbnail"
                                                                     style="width:60px;"
                                                                     src="{% static 'img/no-image.png' %}"></a>
                {% endif %}
                <div class="media-body">
                    <h4><a href="{% url 'my-service' service.id %}">{{ service.service_name }}</a> <small><i>Posted
                        on: {{ service.insDate }}</i></small></h4>
                    <button><a href="{% url 'my-update-service' service.id %}">Update</a> </button>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>You have not posted any services.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

mysite/balticwave/templates/favourites.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container" style="margin-top:20px; margin-bottom:20px">
    <h3>My favourites:</h3>
    {% if new %}
    <div class="card-columns">
        {% for product in new %}
        <div class="card" style="width:341px; height:750px; margin:10px">
            {% if product.product_thumbnail %}
            <a href="{% url 'product-detail' product.id %}"><img src="{{ product.product_thumbnail.url }}" style="width:340px; height:354px"></a>
            {% else %}
            <a href="{% url 'product-detail' product.id %}"><img src="{% static 'img/no-image.png' %}" style="width:340px; height:354px"></a>
            {% endif %}
            <div class="card-body">
                <h3 class="text-center"><a href="{% url 'product-detail' product.id %}">{{ product.product_name }}</a></h3>
                <p class="card-text text-center">{{ product.short_description }}</p>
                <ul class="text-muted">
                    <li>Price: {{ product.price }}€</li>
                    <li>Type: {{ product.display_type }}</li>
                    <li>City: {{ product.get_city_display }}</li>
                    <li>Status: {{ product.get_status_display }}</li>
                    <li>Likes: {{ product.number_of_likes }}</li>
                </ul>
                <button><a href="{% url 'favourite-prod-add' product.id %}">Remove from favourites </a></button>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <h3 class="text-center">You have no favourite items!</h3>
    {% endif %}
</div>
{% endblock %}

mysite/balticwave/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container pt-3 " style="margin-top:30px; padding-left: 200px;" >
    <h3 style="padding-left: 150px">Search for items and services!</h3>
    <form action="{% url 'search' %}" method="get" class="search-bar">
        <input name="query" type="text" placeholder="Search...">
        <button type="submit"><img src="{% static 'img/search.png' %}"></button>
    </form>
</div>

<div class="container" style="margin-top:20px; margin-bottom:20px">
    <h3>Latest items:</h3>
    {% for product in latest_prod %}
        <div class="media border p-3" style="margin-top:20px;">
            {% if product.product_thumbnail %}
            <a href="{% url 'product-detail' product.id %}"><img class="mr-3 mt-3 img-thumbnail" style="width:60px;"
                                            src="{{ product.product_thumbnail.url }}"></a>
            {% else %}
            <a href="{% url 'product-detail' product.id %}"><img class="mr-3 mt-3 img-thumbnail" style="width:60px;"
                                            src="{% static 'img/no-image.png' %}"></a>
            {% endif %}
            <div class="media-body">
                <h4><a href="{% url 'product-detail' product.id %}">{{ product.product_name }}</a> <small><i>Posted on: {{ product.insDate }}</i></small></h4>
                <p>{{ product.short_description }}</p>
                <p>Price: {{ product.price }}€</p>
            </div>
        </div>
    {% endfor %}
</div>

<div class="container" style="margin-top:20px; margin-bottom:20px">
    <h3>Latest services:</h3>
    {% for service in latest_service %}
        <div class="media border p-3" style="margin-top:20px;">
            {% if service.service_thumbnail %}
            <a href="{% url 'service-detail' service.id %}"><img class="mr-3 mt-3 img-thumbnail" style="width:60px;"
                                            src="{{ service.service_thumbnail.url }}"></a>
            {% else %}
            <a href="{% url 'service-detail' service.id %}"><img class="mr-3 mt-3 img-thumbnail" style="width:60px;"
                                            src="{% static 'img/no-image.png' %}"></a>
            {% endif %}
            <div class="media-body">
                <h4><a href="{% url 'service-detail' service.id %}">{{ service.service_name }}</a> <small><i>Posted on: {{ service.insDate }}</i></small></h4>
                <p>Category: {{ service.get_category_display }}</p>
                <p>City: {{ service.get_city_display }}</p>
            </div>
        </div>
    {% endfor %}
</div>


{% endblock %}

mysite/balticwave/templates/my_product.html
{% extends "base.html" %}
{% load static %}
{% load mptt_tags %}
{% block content %}
<div class="container border" style="margin-top:20px; margin-bottom:20px">
    <h2>{{ product.product_name }}</h2>
    <h5>Posted by: {{ product.product_seller }} <small><i>Posted on: {{ product.insDate }}</i></small></h5>
    <div class="row">
        <div class="col-sm-7">
            <div id="demo" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    {% if product.product_thumbnail %}
                    <div class="carousel-item active">
                        <img src="{{ product.product_thumbnail.url }}" class="img_carrousel">
                    </div>
                    {% else %}
                    <div class="carousel-item active">
                        <img src="{% static 'img/no-image.png' %}" class="img_carrousel">
                    </div>
                    {% endif %}
                    {% if product.image1 %}
                    <div class="carousel-item">
                        <img src="{{ product.image1.url }}" class="img_carrousel">
                    </div>
                    {% endif %}
                    {% if product.image2 %}
                    <div class="carousel-item">
                        <img src="{{ product.image2.url }}" class="img_carrousel">
                    </div>
                    {% endif %}
                    {% if product.image3 %}
                    <div class="carousel-item">
                        <img src="{{ product.image2.url }}" class="img_carrousel">
                    </div>
                    {% endif %}
                    {% if product.image4 %}
                    <div class="carousel-item">
                        <img src="{{ product.image2.url }}" class="img_carrousel">
                    </div>
                    {% endif %}
                    {% if product.image5 %}
                    <div class="carousel-item">
                        <img src="{{ product.image2.url }}" class="img_carrousel">
                    </div>
                    {% endif %}
                    {% if product.image6 %}
                    <div class="carousel-item">
                        <img src="{{ product.image2.url }}" class="img_carrousel">
                    </div>
                    {% endif %}
                </div>
                <a class="carousel-control-prev" href="#demo" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                </a>
                <a class="carousel-control-next" href="#demo" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                </a>
            </div>
        </div>
        <div class="col-sm-5">
            <ul class="font-weight-bold">
                <li>Price: {{ product.price }}€</li>
                <li>Category: {{ product.get_category_display }}</li>
                <li>Type: #{{ product.display_type }}</li>
                <li>City: {{ product.get_city_display }}</li>
                <li>Status: {{ product.get_status_display }}</li>
            </ul>
            <h3>Description:</h3>
            <p>{{ product.description }}</p>
        </div>
    </div>
</div>
<div class="container border" style="margin-top:20px; margin-bottom:20px">
    <a href="{% url 'my-update-product' product.id %}">Update item</a>
    <a href="{% url 'my-delete-product' product.id %}">Delete item</a>
</div>
<div class="container border" style="margin-top:20px; margin-bottom:20px">
    <h4>Comments:</h4>
    {% if product.productreview.all %}
    {% for review in product.productreview.all %}
    <hr>
    <strong>{{ review.reviewer }}</strong>, <em>{{ review.date_created}}</em>
    <p>{{ review.content }}</p>
    {% endfor %}
    {% else %}
    <p>There are no comments</p>
    {% endif %}
</div>

{% endblock %}

mysite/balticwave/templates/product_detail.html
{% extends "base.html" %}
{% load static %}
{% load mptt_tags %}
{% block content %}
<div class="container border" style="margin-top:20px; margin-bottom:20px">
    {% if user.is_authenticated %}
    <a style="float: right;" href="{% url 'favourite-prod-add' product.id %}">Add to favourites
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
             class="bi bi-bookmark-plus" viewBox="0 0 16 16">
            <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
            <path d="M8 4a.5.5 0 0 1 .5.5V6H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V7H6a.5.5 0 0 1 0-1h1.5V4.5A.5.5 0 0 1 8 4z"/>
        </svg>
    </a>
    {% else %}
    <a style="float: right;" href="{% url 'login' %}?next={{request.path}}">Log in to save this item!</a><br>
    {% endif %}
    <h2>{{ product.product_name }}</h2>
    <h5>Posted by: {{ product.product_seller }} <small><i>Posted on: {{ product.insDate }}</i></small></h5>
    <div class="row">
        <div class="col-sm-7">
            <div id="demo" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    {% if product.product_thumbnail %}
                    <div class="carousel-item active">
                        <img src="{{ product.product_thumbnail.url }}" class="img_carrousel">
                    </div>
                    {% else %}
                    <div class="carousel-item active">
                        <img src="{% static 'img/no-image.png' %}" class="img_carrousel">
                    </div>
                    {% endif %}
                    {% if product.image1 %}
                    <div class="carousel-item">
                        <img src="{{ product.image1.url }}" class="img_carrousel">
                    </div>
                    {% endif %}
                    {% if product.image2 %}
                    <div class="carousel-item">
                        <img src="{{ product.image2.url }}" class="img_carrousel">
                    </div>
                    {% endif %}
                    {% if product.image3 %}
                    <div class="carousel-item">
                        <img src="{{ product.image2.url }}" class="img_carrousel">
                    </div>
                    {% endif %}
                    {% if product.image4 %}
                    <div class="carousel-item">
                        <img src="{{ product.image2.url }}" class="img_carrousel">
                    </div>
                    {% endif %}
                    {% if product.image5 %}
                    <div class="carousel-item">
                        <img src="{{ product.image2.url }}" class="img_carrousel">
                    </div>
                    {% endif %}
                    {% if product.image6 %}
                    <div class="carousel-item">
                        <img src="{{ product.image2.url }}" class="img_carrousel">
                    </div>
                    {% endif %}
                </div>
                <a class="carousel-control-prev" href="#demo" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                </a>
                <a class="carousel-control-next" href="#demo" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                </a>
            </div>
        </div>
        <div class="col-sm-5">
            <ul class="font-weight-bold">
                <li>Price: {{ product.price }}€</li>
                <li>Category: {{ product.get_category_display }}</li>
                <li>Type: #{{ product.display_type }}</li>
                <li>City: {{ product.get_city_display }}</li>
                <li>Status: {{ product.get_status_display }}</li>
            </ul>
            <h3>Description:</h3>
            <p>{{ product.description }}</p>
            {% if user.is_authenticated %}
            <form action="{% url 'product_like' object.id %}" method="POST">
                {% csrf_token %}
                {% if post_is_liked %}
                <button type="submit" name="blogpost_id" value="{{product.id}}" class="btn btn-danger">Unlike
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-heart" viewBox="0 0 16 16">
                        <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                    </svg>
                </button>
                {% else %}
                <button type="submit" name="blogpost_id" value="{{product.id}}" class="btn btn-outline-danger">Like
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-heart" viewBox="0 0 16 16">
                        <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                    </svg>
                </button>
                {% endif %}
            </form>
            {% else %}
            <a href="{% url 'login' %}?next={{request.path}}">Log in to like this item!</a><br>
            {% endif %}
            <strong> Total: {{ number_of_likes }} Like{{ number_of_likes|pluralize }}</strong>
        </div>
    </div>
</div>

<div class="container border" style="margin-top:20px; margin-bottom:20px">
    <h4>Comments:</h4>
    {% if product.productreview.all %}
    {% for review in product.productreview.all %}
    <hr>
    <strong>{{ review.reviewer }}</strong>, <em>{{ review.date_created}}</em>
    <p>{{ review.content }}</p>
    {% endfor %}
    {% else %}
    <p>There are no comments</p>
    {% endif %}
</div>
{% if user.is_authenticated %}
<div class="container border" style="margin-top:20px; margin-bottom:20px">
    {% if user.is_authenticated %}
    <div class="fieldWrapper">
        <h4>Leave a comment:</h4>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.content }}
            <input type="submit" value="Post">
        </form>
        {% endif %}
    </div>
</div>
{% endif %}

{% endblock %}